<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-V123S32" ignored="0" name="Default test" tests="3" failures="1" timestamp="2020-05-20T14:38:44 IST" time="17.561" errors="0">
  <testcase name="loginTest" time="17.021" classname="com.orangehrm.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Text not Matching. Got text as Your Life&amp;apos;s Work, Powered By Our Life&amp;apos;s Work">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Text not Matching. Got text as Your Life's Work, Powered By Our Life's Work
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.orangehrm.web.OrangeHRMValidationDriver.assertAll(ZohoValidationDriver.java:98)
at com.orangehrm.session.ZohoTestSession.end(ZohoTestSession.java:58)
at com.orangehrm.testcases.LoginTest.loginTest(LoginTest.java:115)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.002" classname="com.orangehrm.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.001" classname="com.orangehrm.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
